version: '3'

services:
  node:
    build: .
    tty: true
    environment:
      #- NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    # ローカルPCのカレントディレクトリをdockerコンテナの/usr/src/appにマウントする
    volumes:
      - ./:/usr/src/app
    # reactappのディレクトリに移動して，reactアプリを起動するコマンドの記述
    command: sh -c "cd reactapp && yarn start"
    # 起動するポートのローカルとリモートを紐づけ
    ports:
      - "3000:3000"